services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /mnt/cloud_storage/caddy_data:/data
      - /mnt/cloud_storage/caddy_config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cloud-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    networks:
      - cloud-net
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    volumes:
      - /mnt/cloud_storage/minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - cloud-net
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/cloud_storage/portainer_data:/data
    ports:
      - "9443:9443"
      - "9002:9000"
    networks:
      - cloud-net
    restart: unless-stopped

networks:
  cloud-net:
    external: true
